SET search_path TO public;

CREATE TABLE public.excel_supervisores (
    id SERIAL PRIMARY KEY,
    nombre character varying(200),
    cargo character varying(200),
    adscripcion character varying(200),
    tipo_identificacion character varying(100),
    folio_identificacion character varying(100),
    credencial_oficial character varying(100),
    tipo_supervisor character varying(100),
    estado character varying(100),
    municipio character varying(100),
    localidad character varying(100),
    telefono character varying(50),
    correo character varying(150),
    nombramiento character varying(255),
    nombre_personal_superior character varying(200),
    cargo_personal_superior character varying(200)
);

INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (6, 'Gustavo Reyes Zavala', NULL, 'SEDER', NULL, NULL, NULL, 'Supervisor', 'Nayarit', 'Tepic', 'Tepic', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (24, 'Ing. Pedro Páramo Bugarín', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', 'INE', '0341050519398', 'OENAY-28', 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', '3891007802', 'paramopedro@hotmail.com', 'B00.03.03.02-2903 -2026', 'Ing, Rosa Estela Flores Salcido', 'Secretaria de Desarrollo Rural');
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (7, 'Francisco Raúl Quintero Villaseñor', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', NULL, NULL, NULL, 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (16, 'Romaldo Ortiz Catón', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', NULL, NULL, 'OENAY-013', 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', '311 184 8855', NULL, NULL, 'Ing, Rosa Estela Flores Salcido', 'Secretaria de Desarrollo Rural');
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (8, 'Valentín Cruz Reséndiz', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', NULL, NULL, 'OENAY-22', 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', '311 847 8532', NULL, NULL, 'Ing, Rosa Estela Flores Salcido', 'Secretaria de Desarrollo Rural');
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (9, 'Jacob Méndez Ortega', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', 'INE', '09600026708518206200H301231MEX', 'OENAY-20', 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', '311 593 9334', 'gato_mendez20@hotmail.com', NULL, 'Ing, Rosa Estela Flores Salcido', 'Secretaria de Desarrollo Rural');
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (10, 'José Gilberto García Vivanco', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', NULL, NULL, 'OENAY-16', 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', '311 190 2000', NULL, NULL, 'Ing, Rosa Estela Flores Salcido', 'Secretaria de Desarrollo Rural');
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (11, 'Juan Carlos Arce Rodríguez', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', NULL, NULL, 'OENAY-18', 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', NULL, NULL, NULL, 'Ing, Rosa Estela Flores Salcido', 'Secretaria de Desarrollo Rural');
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (12, 'Felipa Sotelo López', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', NULL, NULL, 'OENAY-17', 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', '323 104 5172', NULL, NULL, 'Ing, Rosa Estela Flores Salcido', 'Secretaria de Desarrollo Rural');
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (13, 'Nora Leticia Contreras Rodríguez', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', NULL, NULL, 'OENAY-19', 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', '311 141 8128', NULL, NULL, 'Ing, Rosa Estela Flores Salcido', 'Secretaria de Desarrollo Rural');
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (14, 'J. Luis Garay López', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', NULL, NULL, 'OENAY-012', 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', '311 250 4405', NULL, NULL, 'Ing, Rosa Estela Flores Salcido', 'Secretaria de Desarrollo Rural');
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (15, 'Tito Ricardo Valderrama González', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', NULL, NULL, 'OENAY-14', 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', '311 393 6418', NULL, NULL, 'Ing, Rosa Estela Flores Salcido', 'Secretaria de Desarrollo Rural');
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (17, 'Adalberto Morales Fragoso', NULL, 'Comit‚ Pecuario', NULL, NULL, NULL, 'Supervisor', 'Nayarit', 'Tepic', 'Tepic', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (18, 'MVZ. Octavio Herrera Ulloa', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', 'INE', '08750639183897401215H3212312MEX', 'OENAY-10', 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', '311 153 4167', 'hguerra789@gmail.com', 'B00.03.03.02-2903 -2026', 'Ing, Rosa Estela Flores Salcido', 'Secretaria de Desarrollo Rural');
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (19, 'Ing. Jared Guadalupe Peña Barrios', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', NULL, NULL, 'OENAY-23', 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', NULL, NULL, 'B00.03.03.02-2903 -2026', 'Ing, Rosa Estela Flores Salcido', 'Secretaria de Desarrollo Rural');
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (20, 'MVZ. Carlos Antonio Lara González', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', 'INE', '07790088261978309134H3512311MEX', 'OENAY-24', 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', '3111100231', 'pugavet@hotmail.com', 'B00.03.03.02-2903 -2026', 'Ing, Rosa Estela Flores Salcido', 'Secretaria de Desarrollo Rural');
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (21, 'Ing. Ernesto Casillas Orozco', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', 'INE', '1228105742131', 'OENAY-25', 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', '3111394464', 'ernestocasillas2@gmail.com', 'B00.03.03.02-2903 -2026', 'Ing, Rosa Estela Flores Salcido', 'Secretaria de Desarrollo Rural');
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (22, 'MVZ. Juan José López Rivera', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', 'INE', '07240449509968207090H3512311MEX', 'OENAY-26', 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', '3118768360', 'juanlopez2504@hotmail.com', 'B00.03.03.02-2903 -2026', 'Ing, Rosa Estela Flores Salcido', 'Secretaria de Desarrollo Rural');
INSERT INTO "excel_supervisores" ("id", "nombre", "cargo", "adscripcion", "tipo_identificacion", "folio_identificacion", "credencial_oficial", "tipo_supervisor", "estado", "municipio", "localidad", "telefono", "correo", "nombramiento", "nombre_personal_superior", "cargo_personal_superior") VALUES (23, 'MVZ. Iván Jiménez Vargas', 'Oficial Estatal en Movilizaci¢n Agropecuaria, Acu¡cola y Pesquera', 'SEDER', NULL, NULL, 'OENAY-27', 'Oficial Estatal', 'Nayarit', 'Tepic', 'Tepic', NULL, NULL, 'B00.03.03.02-2903 -2026', 'Ing, Rosa Estela Flores Salcido', 'Secretaria de Desarrollo Rural');

SELECT setval('excel_supervisores_id_seq', (SELECT MAX(id) FROM excel_supervisores));
